# Adds namespace to all resources.
namespace: devworkspace-operator

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/name: devworkspace-controller
  app.kubernetes.io/part-of: devworkspace-operator

bases:
- ../components/manager
- ../components/rbac
- ../crd

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: configmap
  envs:
  - config.properties

patchesStrategicMerge:
- manager_image_patch.yaml

vars:
- name: OPERATOR_NAMESPACE
  objref:
    kind: Deployment
    group: apps
    version: v1
    name: manager
  fieldref:
    fieldpath: metadata.namespace
