---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: che-workspace-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: che-workspace-controller
  template:
    metadata:
      labels:
        app: che-workspace-controller
      annotations:
        kubectl.kubernetes.io/restartedAt: ""
    spec:
      serviceAccountName: che-workspace-controller
      containers:
        - name: che-workspace-controller
          image: quay.io/che-incubator/che-workspace-controller:nightly
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "che-workspace-operator"
            - name: SERVICE_ACCOUNT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          ports:
            - name: webhook-server
              containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: che-workspace-controller
  name: workspace-controller
spec:
  ports:
    - targetPort: webhook-server
      protocol: TCP
      port: 443
  selector:
    app: che-workspace-controller
