apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workspaceexposures.workspace.che.eclipse.org
spec:
  group: workspace.che.eclipse.org
  names:
    kind: WorkspaceExposure
    listKind: WorkspaceExposureList
    plural: workspaceexposures
    singular: workspaceexposure
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            exposed:
              description: Should the workspace be exposed ?
              type: boolean
            exposureClass:
              description: 'Class of the exposure: this drives which Workspace exposer
                controller will manage this exposure'
              type: string
            services:
              additionalProperties:
                properties:
                  endpoints:
                    description: Endpoints that correspond to this machine-related
                      service
                    items:
                      properties:
                        attributes:
                          properties:
                            discoverable:
                              description: 'Identifies server as secure or non-secure.
                                Requests to secure servers will be authenticated and
                                must contain machine token - default: false'
                              type: boolean
                            path:
                              description: Defines protocol that should be used for
                                communication with endpoint. Is used for endpoint
                                URL evaluation"
                              type: string
                            protocol:
                              description: 'Identifies endpoint as accessible by its
                                name. - default: false'
                              type: string
                            public:
                              type: boolean
                            secure:
                              description: 'Identifies endpoint as workspace internally
                                or externally accessible - default: true'
                              type: boolean
                          type: object
                        name:
                          type: string
                        port:
                          description: The endpoint name
                          format: int64
                          type: integer
                      required:
                      - name
                      - port
                      type: object
                    type: array
                  serviceName:
                    description: Service name of the machine-related service
                    type: string
                required:
                - serviceName
                - endpoints
                type: object
              description: Services by machine name
              type: object
          required:
          - exposureClass
          - exposed
          - services
          type: object
        status:
          properties:
            exposedEndpoints:
              items:
                properties:
                  attributes:
                    description: Attributes of the exposed endpoint
                    properties:
                      discoverable:
                        description: 'Identifies server as secure or non-secure. Requests
                          to secure servers will be authenticated and must contain
                          machine token - default: false'
                        type: boolean
                      path:
                        description: Defines protocol that should be used for communication
                          with endpoint. Is used for endpoint URL evaluation"
                        type: string
                      protocol:
                        description: 'Identifies endpoint as accessible by its name.
                          - default: false'
                        type: string
                      public:
                        type: boolean
                      secure:
                        description: 'Identifies endpoint as workspace internally
                          or externally accessible - default: true'
                        type: boolean
                    type: object
                  url:
                    description: Url of the exposed endpoint
                    type: string
                required:
                - url
                - attributes
                type: object
              type: array
            phase:
              description: Workspace Exposure status
              type: string
          required:
          - phase
          - exposedEndpoints
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
