apiVersion: apps/v1
kind: Deployment
metadata:
  name: che-workspace-crd-operator
  namespace: operators
spec:
  replicas: 1
  selector:
    matchLabels:
      name: che-workspace-crd-operator
  template:
    metadata:
      labels:
        name: che-workspace-crd-operator
    spec:
      serviceAccountName: che-workspace-crd-operator
      containers:
        - name: che-workspace-crd-operator
          image: quay.io/che-incubator/che-workspace-crd-controller:7.1.0
          command:
          - che-workspace-crd-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "che-workspace-crd-operator"
        - image: quay.io/che-incubator/che-workspace-crd-plugin-registry:7.1.0-offline
          imagePullPolicy: Always
          name: che-plugin-registry
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 16Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: CHE_SIDECAR_CONTAINERS_REGISTRY_TAG
              value: '7.1.0'
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
