---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: view-workspaces
rules:
  - apiGroups:
      - workspace.devfile.io
    resources:
      - devworkspaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - workspace.che.eclipse.org
    resources:
      - workspaceroutings
      - components
    verbs:
      - get
      - list
      - watch
