kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha1
metadata:
  name: cloud-shell
spec:
  started: true
  template:
    components:
      - name: cloud-shell
        plugin:
          id: eclipse/cloud-shell/nightly
      - name: dev
        container:
          image: quay.io/eclipse/che-sidecar-openshift-connector:0.1.2-2601509
          memoryLimit: 256Mi
          args: ["tail", "-f", "/dev/null"]
          env:
            - value: '\[\e[34m\]>\[\e[m\]\[\e[33m\]>\[\e[m\]'
              name: PS1
