kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: theia
spec:
  started: true
  template:
    components:
      - name: theia
        plugin:
          kubernetes:
            name: theia-next
            namespace: devworkspace-plugins
          components:
            - name: plugins
              volume:
                ephemeral: true
      - name: terminal
        plugin:
          kubernetes:
            name: machine-exec
            namespace: devworkspace-plugins
      - name: projects
        volume:
          ephemeral: true
